"""
Playwright browser recording for Credivo LMS demo.
Each section is timed to EXACTLY match its TTS audio segment duration.
Durations loaded from demo/segment_durations.json (generated by generate_tts.py).
"""
import asyncio, json, os
from pathlib import Path
from playwright.async_api import async_playwright

BASE   = "https://credivo.vercel.app"
CREDS  = {
    "borrower": ("rahul.sharma@email.com", "Borrower@123"),
    "sales":    ("sales@credivo.com",      "Sales@123"),
    "sanction": ("sanction@credivo.com",   "Sanction@123"),
    "disburse": ("disburse@credivo.com",   "Disburse@123"),
    "collect":  ("collect@credivo.com",    "Collect@123"),
    "admin":    ("admin@credivo.com",      "Admin@123"),
}
OUT_DIR = Path(__file__).parent / "recording"
OUT_DIR.mkdir(exist_ok=True)

# Load TTS durations (ms per section)
_dur_path = Path(__file__).parent / "segment_durations.json"
with open(_dur_path) as _f:
    _DUR = {k: int(v * 1000) for k, v in json.load(_f)["segments"].items()}

# ── helpers ───────────────────────────────────────────────────────────────────
async def wait(page, msec):
    await page.wait_for_timeout(msec)

async def scroll(page, px, steps=8, pause_ms=None):
    step_px = px // steps
    delay   = (pause_ms // steps) if pause_ms else 160
    for _ in range(steps):
        await page.mouse.wheel(0, step_px)
        await page.wait_for_timeout(delay)

async def scroll_top(page, ms_after=600):
    await page.evaluate("window.scrollTo({top:0,behavior:'smooth'})")
    await page.wait_for_timeout(ms_after)

async def fill(page, selector, value):
    try:
        await page.fill(selector, value)
        await page.wait_for_timeout(300)
    except Exception:
        pass

async def click(page, selector, timeout=4000):
    try:
        await page.click(selector, timeout=timeout)
        return True
    except Exception:
        return False

async def do_login(page, email, pw):
    await page.goto(f"{BASE}/login", wait_until="domcontentloaded")
    await wait(page, 1400)
    await fill(page, 'input[placeholder="you@credivo.com"]', email)
    await fill(page, 'input[placeholder="\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022"]', pw)
    await click(page, 'button:has-text("Sign in")')
    await wait(page, 3000)

async def do_logout(page):
    for sel in ['button:has-text("Sign out")', 'button:has-text("Logout")']:
        if await click(page, sel, timeout=2000):
            await wait(page, 1200)
            return
    await page.goto(f"{BASE}/login", wait_until="domcontentloaded")
    await wait(page, 1000)

# ── main ──────────────────────────────────────────────────────────────────────
async def record():
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=False,
            slow_mo=50,
            args=["--start-maximized", "--disable-infobars"],
        )
        ctx = await browser.new_context(
            viewport={"width": 1280, "height": 720},
            record_video_dir=str(OUT_DIR),
            record_video_size={"width": 1280, "height": 720},
        )
        page = await ctx.new_page()

        # ── [intro] 22.3s — Landing page loads & first scroll ─────────────────
        print("[intro] Landing page")
        await page.goto(BASE, wait_until="domcontentloaded")
        await wait(page, 2500)
        await scroll(page, 700, steps=9, pause_ms=12000)
        await wait(page, 4500)
        await scroll(page, 300, steps=4, pause_ms=3000)

        # ── [rbac] 16.8s — continue scrolling landing ─────────────────────────
        print("[rbac] Landing continues")
        await scroll(page, 400, steps=5, pause_ms=9000)
        await wait(page, 4000)
        await scroll_top(page, 800)
        await wait(page, 2500)

        # ── [landing] 12.8s — CTA area ────────────────────────────────────────
        print("[landing] Landing CTA")
        await scroll(page, 250, steps=4, pause_ms=6000)
        await wait(page, 3500)
        await scroll_top(page, 600)
        await wait(page, 2500)

        # ── [register] 13.1s — /register form ────────────────────────────────
        print("[register] Register form")
        await page.goto(f"{BASE}/register", wait_until="domcontentloaded")
        await wait(page, 1800)
        await fill(page, 'input[placeholder="you@email.com"]',   "demo.user@credivo.com")
        await fill(page, 'input[type="date"]',                    "1993-06-15")
        await fill(page, 'input[placeholder="Min 6 characters"]', "Demo@1234")
        await scroll(page, 300, steps=4, pause_ms=5500)
        await wait(page, 2500)
        await scroll_top(page, 500)

        # ── [login] 11.9s — /login form fill ─────────────────────────────────
        print("[login] Login page")
        await page.goto(f"{BASE}/login", wait_until="domcontentloaded")
        await wait(page, 2000)
        await fill(page, 'input[placeholder="you@credivo.com"]',  "rahul.sharma@email.com")
        await fill(page, 'input[placeholder="\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022"]', "Borrower@123")
        await wait(page, 2000)
        await click(page, 'button:has-text("Sign in")')
        await wait(page, 3500)

        # ── [borrower_dash] 9.96s — /dashboard ───────────────────────────────
        print("[borrower_dash] Borrower dashboard")
        await wait(page, 1200)
        await scroll(page, 500, steps=6, pause_ms=5500)
        await scroll_top(page, 500)
        await wait(page, 1500)

        # ── [loans_list] 9.8s — /loans ────────────────────────────────────────
        print("[loans_list] Loans list")
        await click(page, 'a[href="/loans"]')
        await wait(page, 2500)
        await scroll(page, 300, steps=4, pause_ms=4500)
        await scroll_top(page, 500)
        await wait(page, 1500)

        # ── [loan_detail] 16.8s — /loans/LMS-... ─────────────────────────────
        print("[loan_detail] Loan detail")
        try:
            href = await page.get_attribute('a[href^="/loans/LMS"]', "href", timeout=3000)
            await page.goto(f"{BASE}{href}", wait_until="domcontentloaded")
        except Exception:
            pass
        await wait(page, 2500)
        await scroll(page, 400, steps=5, pause_ms=7000)
        await wait(page, 3000)
        await scroll(page, 300, steps=4, pause_ms=4000)
        await scroll_top(page, 500)

        # ── [apply_bre] 18.8s — /apply wizard ────────────────────────────────
        print("[apply_bre] Apply / BRE")
        await click(page, 'a[href="/apply"]')
        await wait(page, 2500)
        await fill(page, 'input[type="number"]', "150000")
        await wait(page, 600)
        await scroll(page, 300, steps=4, pause_ms=5500)
        await wait(page, 2500)
        await click(page, 'button:has-text("Next"), button:has-text("Continue"), button:has-text("Check Eligibility")')
        await wait(page, 4500)
        await scroll(page, 200, steps=3, pause_ms=2500)
        await scroll_top(page, 500)

        # ── [textract] 23.1s — salary slip upload page ────────────────────────
        print("[textract] Textract / upload")
        await wait(page, 3000)
        await scroll(page, 350, steps=5, pause_ms=8000)
        await wait(page, 6000)
        await scroll(page, 300, steps=4, pause_ms=6000)
        await scroll_top(page, 600)

        # ── [bedrock_apply] 17.9s — Bedrock result / transition ───────────────
        print("[bedrock_apply] Bedrock result")
        await scroll(page, 350, steps=5, pause_ms=9000)
        await wait(page, 5000)
        await scroll_top(page, 700)
        await wait(page, 2500)
        await do_logout(page)

        # ── [sales_dash] 15.8s — /ops/sales charts ────────────────────────────
        print("[sales_dash] Sales charts")
        await do_login(page, *CREDS["sales"])
        await wait(page, 1500)
        await scroll(page, 500, steps=6, pause_ms=6500)
        await wait(page, 3000)
        await scroll(page, 400, steps=5, pause_ms=4000)
        await scroll_top(page, 600)

        # ── [sales_leads] 9.1s — leads table ─────────────────────────────────
        print("[sales_leads] Leads table")
        await scroll(page, 800, steps=8, pause_ms=6000)
        await wait(page, 2500)
        await scroll_top(page, 500)
        await do_logout(page)

        # ── [sanction_dash] 15.1s — /ops/sanction queue ──────────────────────
        print("[sanction_dash] Sanction queue")
        await do_login(page, *CREDS["sanction"])
        await wait(page, 1500)
        await scroll(page, 600, steps=7, pause_ms=7000)
        await wait(page, 2500)
        await scroll(page, 400, steps=5, pause_ms=4500)
        await scroll_top(page, 600)

        # ── [review_textract] 19.3s — review page, Textract panel ─────────────
        print("[review_textract] Sanction review — Textract")
        try:
            href2 = await page.locator('a:has-text("Review")').first.get_attribute("href", timeout=3000)
            await page.goto(f"{BASE}{href2}", wait_until="domcontentloaded")
        except Exception:
            await page.goto(f"{BASE}/ops/sanction/LMS-2026-10001", wait_until="domcontentloaded")
        await wait(page, 3500)
        await scroll(page, 320, steps=5, pause_ms=9500)
        await wait(page, 4500)
        await scroll(page, 150, steps=3, pause_ms=3000)

        # ── [review_bedrock] 17.4s — Bedrock risk panel ───────────────────────
        print("[review_bedrock] Sanction review — Bedrock")
        await scroll(page, 320, steps=4, pause_ms=9000)
        await wait(page, 5000)
        await scroll(page, 100, steps=2, pause_ms=2500)
        await scroll_top(page, 600)
        await do_logout(page)

        # ── [disburse_dash] 12.4s — /ops/disbursement ────────────────────────
        print("[disburse_dash] Disbursement dashboard")
        await do_login(page, *CREDS["disburse"])
        await wait(page, 1500)
        await scroll(page, 600, steps=7, pause_ms=6500)
        await wait(page, 2000)
        await scroll_top(page, 600)

        # ── [disburse_pdf] 19.1s — history & PDF ─────────────────────────────
        print("[disburse_pdf] Disbursement PDF")
        await click(page, 'button:has-text("History")', timeout=3000)
        await wait(page, 2500)
        await scroll(page, 500, steps=6, pause_ms=8000)
        await wait(page, 4500)
        await scroll(page, 300, steps=4, pause_ms=3500)
        await scroll_top(page, 600)
        await do_logout(page)

        # ── [collect_dash] 12.9s — /ops/collection ────────────────────────────
        print("[collect_dash] Collection dashboard")
        await do_login(page, *CREDS["collect"])
        await wait(page, 1500)
        await scroll(page, 600, steps=7, pause_ms=7000)
        await wait(page, 2500)
        await scroll_top(page, 600)

        # ── [collect_payment] 12.5s — collection loan detail ─────────────────
        print("[collect_payment] Collection loan detail")
        try:
            href3 = await page.locator('a[href*="/ops/collection/"]').first.get_attribute("href", timeout=3000)
            await page.goto(f"{BASE}{href3}", wait_until="domcontentloaded")
        except Exception:
            pass
        await wait(page, 2500)
        await scroll(page, 500, steps=6, pause_ms=7000)
        await scroll_top(page, 600)
        await do_logout(page)

        # ── [admin_dash] 17.3s — /ops/admin ──────────────────────────────────
        print("[admin_dash] Admin dashboard")
        await do_login(page, *CREDS["admin"])
        await wait(page, 1500)
        await scroll(page, 600, steps=7, pause_ms=8000)
        await wait(page, 3000)
        await scroll(page, 400, steps=5, pause_ms=4500)
        await scroll_top(page, 700)

        # ── [tech_stack] 23.3s — back to landing ─────────────────────────────
        print("[tech_stack] Landing tech crawl")
        await do_logout(page)
        await page.goto(BASE, wait_until="domcontentloaded")
        await wait(page, 2000)
        await scroll(page, 700, steps=8, pause_ms=10000)
        await wait(page, 5000)
        await scroll(page, 500, steps=6, pause_ms=5000)
        await scroll_top(page, 700)

        # ── [outro] 12.6s — final pan ─────────────────────────────────────────
        print("[outro] Outro")
        await wait(page, 3000)
        await scroll(page, 400, steps=5, pause_ms=6000)
        await wait(page, 3500)

        print("Done — closing browser")
        await ctx.close()
        await browser.close()

    videos = sorted(OUT_DIR.glob("*.webm"), key=lambda f: f.stat().st_mtime)
    if videos:
        v = videos[-1]
        print(f"\nVideo: {v}")
        return str(v)
    print("No video found")
    return None


if __name__ == "__main__":
    asyncio.run(record())
